# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stella < Formula
  desc "Self-hosted AI assistant"
  homepage "https://stella.cherryin.com"
  version "0.35.0"
  license "AGPL-3.0-or-later"

  depends_on "bubblewrap" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CherryHQ/stella/releases/download/v0.35.0/stella_0.35.0_darwin_amd64.tar.gz"
      sha256 "6adc423f221a81dcbe0534c1d9d33e0a794b3b0ce406a1df89facc37e898bf6a"

      define_method(:install) do
        bin.install "stella"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CherryHQ/stella/releases/download/v0.35.0/stella_0.35.0_darwin_arm64.tar.gz"
      sha256 "01399a499225a360f3df8f48ae7de8a783148b9d56904a518d4cf9c07fb99e0f"

      define_method(:install) do
        bin.install "stella"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CherryHQ/stella/releases/download/v0.35.0/stella_0.35.0_linux_amd64.tar.gz"
      sha256 "d99dd4c1a0e20790a52b7943ac14a28e310413ea146d213a13590f4cfba59b5b"
      define_method(:install) do
        bin.install "stella"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CherryHQ/stella/releases/download/v0.35.0/stella_0.35.0_linux_arm64.tar.gz"
      sha256 "c1dac5cddfa1c1f48b37758aef710f2c0c7b582e05edb673021fc929d43ce1cd"
      define_method(:install) do
        bin.install "stella"
      end
    end
  end

  service do
    run [opt_bin/"stella", "server"]
    keep_alive crashed: true
    log_path var/"log/stella.log"
    error_log_path var/"log/stella.log"
  end

  test do
    system "#{bin}/stella", "version"
  end
end
