# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stella < Formula
  desc "Self-hosted AI assistant"
  homepage "https://stella.cherryin.com"
  version "0.60.0"
  license "AGPL-3.0-or-later"

  depends_on "bubblewrap" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CherryHQ/stella/releases/download/v0.60.0/stella_0.60.0_darwin_amd64.tar.gz"
      sha256 "5d1446899989ac638f9e01f6b577404fcc7ecccd3cdcbf069b8d1376734cce9e"

      define_method(:install) do
        bin.install "stellad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CherryHQ/stella/releases/download/v0.60.0/stella_0.60.0_darwin_arm64.tar.gz"
      sha256 "f7d06ef5428af42a5c7c963e726639cb8f80317fd47306e002058457c3614f99"

      define_method(:install) do
        bin.install "stellad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CherryHQ/stella/releases/download/v0.60.0/stella_0.60.0_linux_amd64.tar.gz"
      sha256 "c26f6f5aa3266b5c2b906955f6ae04d3840bbd981e93cecf194ed939ebe05341"
      define_method(:install) do
        bin.install "stellad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CherryHQ/stella/releases/download/v0.60.0/stella_0.60.0_linux_arm64.tar.gz"
      sha256 "ef466aba5e4017324587f2cc82d4bef8aeafc31ee5e304c02a039be0b9eb355b"
      define_method(:install) do
        bin.install "stellad"
      end
    end
  end

  service do
    run [opt_bin/"stellad", "server"]
    keep_alive crashed: true
    log_path var/"log/stella.log"
    error_log_path var/"log/stella.log"
  end

  test do
    system "#{bin}/stellad", "version"
  end
end
